- server:
    port: 8080
  spring:
    application:
      name: sales
- spring:
    profiles: default
    jpa:
      properties:
        database: POSTGRESQL
        show-sql: true
        hibernate:
          ddl-auto: create-drop
    cloud:
      stream:
        kafka:
          binder:
            brokers: 'localhost:9092'
          streams:
            binder:
              configuration:
                default:
                  key:
                    serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                  value:
                    serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        bindings:
          event-in:
            group: sales
            destination: newtestwijmo
            contentType: application/json
          event-out:
            destination: newtestwijmo
            contentType: application/json
  logging:
    level:
      org.hibernate.type: trace
      org.springframework.cloud: debug
  server:
    port: 8083
- spring:
    profiles: docker
    cloud:
      stream:
        kafka:
          binder:
            brokers: 'my-kafka:9092'
          streams:
            binder:
              configuration:
                default:
                  key:
                    serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                  value:
                    serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        bindings:
          event-in:
            group: sales
            destination: newtestwijmo
            contentType: application/json
          event-out:
            destination: newtestwijmo
            contentType: application/json
